channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python >=3.5
  - rpy2 >=0.7.6
  - boto3
  - moto >=1.0.1
  - httpretty
  - wrapt
  - pyyaml
  - nose
  - ftputil
  - pysftp
  - requests
  - dropbox
  - numpy
  - appdirs
  - pytools
  - docutils
  - pandoc
  - r-base >=3.4.1
  - r-rmarkdown
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libsm
  - psutil
  - google-cloud-storage
  - ratelimiter
  - configargparse
  - appdirs
