organisms:
  homo_sapiens:
  pan_troglodytes:
  gorilla_gorilla:
  macaca_mulatta:
  mus_musculus:
  rattus_norvegicus:
  bos_taurus:
  gallus_gallus:
  xenopus_tropicalis:

repeatUnit: "L"
repeatThreshold: "5"
region: "WHOLE"
MSAseqNumber: "100"
MSAalgorithm: "Muscle"
downloadInputData: "YES"
