#Specify the organisms in the analysis
organisms:
  homo_sapiens:
  mus_musculus:
#Specify the organism of interest
organismOfInterest:
  homo_sapiens:
#Specify the repeat building unit
repeatUnit: "L"
#Specify the consecutive number of amino acids that should be considered as SAAR
repeatThreshold: "5"
#Specify the region of interest
region: "SP"
MSAseqNumber: "100"
#Specify the number of sequences used for the mean pairwise evlutionary distance estination between the organisms
MSAalgorithm: "Muscle"
#Specify whether the data should be downloaded or will be fed to the pipeline
downloadInputData: "YES"
